package sivatagiVizhalozat;
import java.util.ArrayList;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sivatagi Vizhalozat
//  @ File Name : Cistern.java
//  @ Date : 03/04/2023
//  @ Author : 
//
//

/** 
 * The field or element of the game that collects water for the citites
*/
public class Cistern extends FieldElement {


	/**
	 * Default constructor;
	 */
	public Cistern() {
		super();
		Skeleton.Println(this.toString()+"Cistern()");
	}

	
	/**
	 * Two parameter constructor
	 * @param mc The maximum number of connections this element can have
	 * @param g The Game object where this element is being used
	 */
	public Cistern(int mc, Game g) {
		super(mc, g);
		Skeleton.Println(this.toString()+"Cistern("+ int.class.getSimpleName() + " " + mc + ", " + Game.class.getSimpleName() + " " + g +")");
	}

	/**
	 * It creates a new pump and returns it
	 * @return The newly created pump
	 */
	public Pump ProvidePump() {
		Skeleton.Println(this.toString()+"ProvidePump()");
		Skeleton.indentation++;
		Pump ret = new Pump();
		if(ret != null) {
			Skeleton.indentation--;
			Skeleton.Println("return " + ret);
			return ret;
		}
		Skeleton.indentation--;
		Skeleton.Println("return null");
		return null;
	}
	
	/** 
	 * The implementation of the Step1 function of the Steppable interface
	*/
	public void Step1() {
		Skeleton.Println(this.toString()+"Step1()");
		Skeleton.indentation++;
		ArrayList<FieldElement> neighbours = GetNeighbor();
		if(neighbours != null) {
			for (var neighbour : neighbours) {
				getGame().WaterCollected(neighbour.SuckWater(Integer.MAX_VALUE));
			}
		}
		Skeleton.indentation--;
	}
}
