package sivatagiVizhalozat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cistern.java
//  @ Date : 03/04/2023
//  @ Author : 
//
//




/** */
public class Cistern {
	/** */
	public Pipe Pipe;
	
	/** */
	public Pump ProvidePump() {
	}
	
	/** */
	public void Step1() {
	}
}
