package sivatagiVizhalozat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 03/04/2023
//  @ Author : 
//
//




/** */
public class Game {
	/** */
	private int spilledWater;
	
	/** */
	private int collectedWater;
	
	/** */
	private Saboteur saboteurs;

	/** */
	private Plumber plumbers;
	
	/** */
	private Steppable Steppable;
	
	/** */
	public void Tick() {
	}
	
	/** */
	public void WaterSpilled(int water) {
	}
	
	/** */
	public void AddSteppable(Steppable s) {
	}
	
	/** */
	public void WaterCollected(int water) {
	}
}
