package sivatagiVizhalozat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pipe.java
//  @ Date : 03/04/2023
//  @ Author : 
//
//




/** */
public class Pipe extends FieldElement {
	/** */
	private boolean isPunctured;
	
	/** */
	private boolean isGrabbed;
	
	/** */
	private int capacity;
	
	/** */
	private int water;
	
	/** */
	public boolean Puncture() {
	}
	
	/** */
	public boolean Split(Pump p) {
	}
	
	/** */
	public void Step1() {
	}
	
	/** */
	public boolean StepOn() {
	}
	
	/** */
	public boolean StepOff() {
	}
	
	/** */
	public Pipe Grab() {
	}
	
	/** */
	public boolean Drop() {
	}
	
	/** */
	public boolean Repair() {
	}
	
	/** */
	public int SuckWater(int water) {
	}
	
	/** */
	public int PumpWater(int water) {
	}
}
