package sivatagiVizhalozat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 03/04/2023
//  @ Author : 
//
//




/** */
public abstract class Player implements Steppable {
	/** */
	private FieldElement location;
	
	/** */
	private Game game;
	
	public Player() {
		Skeleton.Println(this.toString()+"Player()");
		location = null;
		game = null;
	}
	
	public Player(Game g, FieldElement f) {
		Skeleton.Println(this.toString()+"Player(" + Game.class.getSimpleName()+ " " + g + ", " + FieldElement.class.getSimpleName() + " " + f + ")");
		game = g;
		location = f;
	}
	
	/** */
	public void PlayerMove(FieldElement f) {
	}
	
	/** */
	public FieldElement GetLocation() {
		return null;
	}

	/** */
	public void PumpDirection(int input, int output) {
	}
}
