package sivatagiVizhalozat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 03/04/2023
//  @ Author : 
//
//




/** */
public abstract class Player implements Steppable {
	/** */
	private FieldElement location;
	
	/** */
	private Game game;
	
	/** */
	public void PlayerMove(FieldElement f) {
	}
	
	/** */
	public FieldElement GetLocation() {
		return null;
	}

	/** */
	public void PumpDirection(int input, int output) {
	}
}
