package sivatagiVizhalozat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pump.java
//  @ Date : 03/04/2023
//  @ Author : 
//
//




/** */
public class Pump extends FieldElement implements Steppable {
	/** */
	private boolean isWorking;
	
	/** */
	private int tankCapacity;
	
	/** */
	private int input;
	
	/** */
	private int output;
	
	/** */
	private int water;
	
	/** */
	public Pipe Pipe;
	
	/** */
	public boolean ChangeDirection(int input, int output) {
		return false;
	}
	
	/** */
	public void StopWorking() {
	}
	
	/** */
	public void Step1() {
	}
	
	/** */
	public void Step2() {
	}
	
	/** */
	public boolean Repair() {
		return false;
	}
}
