package sivatagiVizhalozat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Saboteur.java
//  @ Date : 03/04/2023
//  @ Author : 
//
//




/** */
public class Saboteur extends Player {
    /** */
    private void PuncturePipe();
}
