package sivatagiVizhalozat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Spring.java
//  @ Date : 03/04/2023
//  @ Author : 
//
//




/** */
public class Spring extends FieldElement {
	
	/** */
	public void Step2() {
	}
}
