package sivatagiVizhalozat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sivatagi Vizhalozat 
//  @ File Name : Spring.java
//  @ Date : 03/04/2023
//  @ Author : 
//
//



/** */
public class Spring extends FieldElement {

	/**
	 * Default constructor
	 */
	public Spring() {
		super();
		Skeleton.Println(this.toString()+"Spring()");
	}

	/**
	 * Two parameter constructor
	 * @param mc The maximum number of connections this element can have
	 * @param g The Game object where this element is being used
	 */
	public Spring(int mc, Game g) {
		super(mc, g);
		Skeleton.Println(this.toString()+"Spring("+ int.class.getSimpleName() + " " + mc + ", " + Game.class.getSimpleName() + " " + g +")");
	}
	
	/** 
	 * The implementation of the Step2 function of the Steppable interface
	*/
	public void Step2() {
		Skeleton.Println(this.toString()+"Step2()");
		Skeleton.indentation++;
		for (var connection : GetNeighbor()) {
			connection.PumpWater(Integer.MAX_VALUE);
		}
		Skeleton.indentation--;
	}
}
