package sivatagiVizhalozat;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Steppable.java
//  @ Date : 03/04/2023
//  @ Author : 
//
//




/** */
public interface Steppable {
	/** */
	public void Step1();
	
	/** */
	public void Step2();
}
